import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ar'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'walk_in_customer': 'زبون عابر (Détail)',
      'kg': 'كغ',
      'item_deleted_msg': 'تم حذفه من السلة',
      'transferred_cart_from': 'سلة محولة من زميلك',
      'ticket': 'تذكرة',
      'amount': 'المبلغ',
      'contains_items': 'تحتوي على سلع',
      'transferred_cart_desc': 'قام زميلك بتحويل هذه السلة لتخليص الزبون بسبب نفاد الصرف لديه.',
      'postpone_f9': 'تأجيل في القائمة (F9)',
      'checkout_now_btn': 'فتح السلة والمحاسبة الآن',
      'cart_received_success': 'تم استلام السلة بنجاح!',
      'cart_empty_warning': 'السلة فارغة! لا توجد سلع لتحويلها.',
      'transfer_cart_title': 'تحويل السلة لكاشير آخر 🔀',
      'current_cart': 'السلة الحالية',
      'enter_peer_ip_hint': 'أدخل عنوان IP لجهاز الكاشير الثاني في الشبكة المحلية:',
      'peer_ip_label': 'عنوان IP لجهاز الزميل (Peer IP)',
      'cashier': 'كاشير',
      'transfer_cart_btn': 'تحويل السلة لزميلك الآن',
      'cart_transferred_success': 'تم تحويل السلة بنجاح إلى كاشير!',
      'cart_transfer_failed': 'تعذر إرسال السلة. تأكد من تشغيل البرنامج لدى زميلك.',
      'send_digital_receipt_wa': 'إرسال الوصل الرقمي عبر WhatsApp 💬',
      'send_now_btn': 'إرسال الآن',
      'invalid_phone': 'رقم الهاتف غير صالح!',
      'receipt_sent_wa': 'تم فتح تطبيق WhatsApp وإرسال الوصل!',
      'receipt_copied_clipboard': 'تعذر فتح WhatsApp، تم نسخ نص الوصل إلى الحافظة تلقائياً',
      'cart_held_success': 'تم تعليق السلة بنجاح وحفظها مؤقتاً (F2)',
      'category_products': 'منتجات صنف',
      'click_to_add_cart': 'انقر على أي منتج لإضافته مباشرة إلى السلة الحالية',
      'search_category_items': 'بحث في هذا الصنف بالاسم أو الباركود...',
      'no_products_in_cat': 'لا توجد منتجات مسجلة في صنف',
      'added_to_cart': 'تمت إضافته للسلة',
      'stock': 'مخزون',
      'touch_numpad': 'لوحة الأرقام اللمسية (Touch Numpad)',
      'hold': 'تعليق',
      'transfer_f11_btn': 'تحويل (F11)',
      'add_quick_product': '+ إضافة منتج سريع',
      'free_item_f7': 'سلعة حرة بدون باركود (F7)',
      'quick_badge': 'سريع ⚡',
      'percent_discount': 'نسبة %',
      'amount_discount': 'مبلغ د.ج',
      'discount_percentage': 'نسبة الخصم (%)',
      'discount_amount': 'مبلغ الخصم (DA)',
      'settings_comprehensive_title': 'الإعدادات والإدارة الشاملة ⚙️',
      'hardware_printing_header': 'الأجهزة والطباعة الحرارية 🖨️',
      'sound_notifs_header': 'الأصوات والإشعارات والتنبيهات 🔊🔔',
      'security_backup_header': 'الأمان والنسخ الاحتياطي 🔒💾',
      'language_info_header': 'اللغة ومعلومات التطبيق 🌐✨',
      'appearance_theme_header': 'المظهر والسمات (Thème & Apparence) 🎨🌙',
      'dark_amoled_mode': 'وضع الشاشة الداكن الفائق (AMOLED Black)',
      'dark_amoled_desc': 'سواد خالص مريح للعين وموفر لاستهلاك الطاقة',
      'header_branding_title': 'ألوان شريط الكاشير وشعار المحل 🎨',
      'header_branding_desc': 'اختر اللون المفضل لشريط الكاشير وتخصيص هوية المتجر',
      'select_language_title': 'اختر لغة التطبيق (Language)',
      'pay_card': 'بطاقة بنكية / الذهبية (TPE)',
      'pay_qr': 'بريدي باي (BaridiPay QR)',
      'pay_split': 'دفع مجزأ (Paiement Partagé)',
      'pack_box_tab': 'باكي (علبة 🟫)',
      'carton_10_tab': 'كرطوشة (10 علب 📦)',
      'single_piece_tab': 'بالسيجارة (Détail 🚬)',
      'retail_detail': 'بيع بالتجزئة (Détail)',
      'wholesale_gros': 'بيع بالجملة (Gros)',
      'wholesale_badge': 'سعر الجملة 📦',
      'barcode_stock_label': 'الباركود: %barcode% • المخزون: %stock%',
      // General & Navigation
      'app_name': 'Nayli Kiosk Pro',
      'app_title': 'Nayli Kiosk - إدارة الفوترة ونقاط البيع الذكية',
      'pos_welcome': '🌟 مرحباً بكم • Bienvenue',
      'pos_title': 'نظام الفوترة ونقاط البيع السريعة',
      'cart': 'سلة المشتريات',
      'items_count': 'أصناف',
      'total_price': 'المجموع الإجمالي',
      'grand_total': 'المجموع الإجمالي',
      'checkout': 'تفاصيل الفاتورة والدفع',
      'review_order': 'متابعة الدفع',
      'settings': 'الإعدادات والخيارات',
      'products_management': 'إدارة المنتجات والمخزون',
      'stock_in': 'استلام السلع / Arrivage',
      'daily_report': 'تقرير اليومية والأرباح',
      'shop_details': 'معلومات المتجر',
      'credit_ledger': 'دفتر الكريدي والديون',
      'credit_ledger_title': 'دفتر ديون الزبائن (Crédit)',
      'hardware': 'العتاد والأجهزة',
      'print_device': 'طابعة الفواتير',
      'connected': 'متصل',
      'disconnected': 'غير متصل',
      'language': 'لغة التطبيق',
      'arabic': 'العربية (AR)',
      'french': 'Français (FR)',
      'english': 'English (EN)',
      'close': 'إغلاق',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'search': 'بحث...',
      'required': 'هذا الحقل مطلوب',
      'balance': 'الرصيد',

      // POS, Scanner & Actions
      'camera_off': 'الكاميرا متوقفة',
      'turn_on_camera': 'تشغيل الكاميرا',
      'align_barcode': 'وجّه الكاميرا نحو باركود السلعة',
      'cart_empty': 'السلة فارغة حالياً',
      'cart_empty_hint': 'امسح الباركود بالكاميرا أو اختر سلعة سريعة من القائمة',
      'clear_cart': 'إفراغ السلة',
      'clear_cart_confirm': 'هل أنت متأكد من حذف جميع السلع الممسوحة في هذه السلة والبدء من جديد؟',
      'park_cart': 'تعليق في سلة مؤقتة',
      'parked_cart_msg': 'تم تعليق الفاتورة بنجاح ⏸️',
      'resume_cart': 'استرجاع السلة',
      'resumed_cart_msg': 'تم استرجاع الفاتورة المعلقة ▶️',
      'held_carts': 'السلات المؤقتة المعلقة',
      'return_mode': 'وضع الإرجاع والاستبدال 🔄',
      'return_mode_active': 'وضع الإرجاع مفعّل (Mode Retour)',
      'return_mode_hint': 'سيتم استرجاع السلع وإعادتها للمخزون وإعادة المبلغ للزبون',
      'discount': 'تخفيض / Remise',
      'apply_discount': 'تطبيق التخفيض',
      'remove_discount': 'حذف التخفيض',
      'stock_zero_warning': 'المخزون: 0',
      'item_name': 'اسم السلعة',
      'item_price': 'السعر',
      'total': 'المجموع',
      'quantity': 'الكمية',
      'new_invoice': 'فاتورة جديدة',
      'confirm_and_print': 'تأكيد البيع وطباعة الوصل',
      'reprint': 'إعادة طباعة الوصل',
      'printed_success': '✅ تم حفظ المعاملة وخصم المخزون والطباعة بنجاح!',
      'tier_detail': 'تجزئة (F5)',
      'tier_demi_gros': 'نصف جملة (F5)',
      'tier_gros': 'جملة (F5)',
      'scan_input_hint': 'امسح الباركود أو اكتب الكمية*باركود (F1)...',
      'table_product': 'المنتج',
      'table_qty': 'الكمية',
      'table_price': 'السعر',
      'table_total': 'الإجمالي',
      'cart_items_count': 'عدد المواد',
      'cart_net_total': 'الإجمالي الصافي:',
      'btn_discount': 'تخفيض (F4)',
      'btn_hold': 'تعليق (F2)',
      'btn_pay_checkout': 'دفع وفوترة (F12)',
      'pos_incoming_carts': 'سلات واردة',
      'pos_open_drawer': 'فتح درج النقود (F10)',
      'pos_commercial_docs': 'الوثائق التجارية والفواتير',
      'pos_backup_sync': 'النسخ الاحتياطي السحابي والمحلي',
      'pos_shifts_zreport': 'إدارة الورديات والصندوق (Z-Report)',
      'pos_master_catalog': 'مكتبة السلع الجزائرية (59K منتج)',
      'pos_inventory': 'المخزون والمنتجات',
      'pos_reports': 'التقارير اليومية',
      'pos_settings': 'الإعدادات والعتاد',
      'hotkeys_hint': '[F1: مسح]   [F2: تعليق]   [F3: عميل]   [F4: تخفيض]   [F5: جملة/تجزئة]   [F6: إرجاع]   [F7: سلعة سريعة]   [F8: فحص سعر]   [F9: سلات واردة]   [F12: دفع]',

      // Categories
      'cat_all': 'الكل',
      'cat_stationery': 'أدوات مدرسية ومكتبية',
      'cat_beverages': 'المشروبات',
      'cat_pulses': 'البقوليات',
      'cat_cleaning': 'المنظفات',
      'cat_sweets': 'الحلويات',
      'cat_scale': 'الميزان',
      'cat_dairy': 'الألبان',
      'cat_spices': 'التوابل',
      'cat_tobacco': 'تبغ وسجائر',

      // Payment & Credit Modes
      'payment_mode': 'طريقة الدفع',
      'pay_cash': 'كاش (نقداً)',
      'pay_credit': 'كريدي كامل (دين)',
      'pay_acompte': 'تسبيق + كريدي',
      'select_customer': 'اختر الزبون',
      'select_customer_hint': 'اضغط لاختيار الزبون المسجل عليه الدين',
      'acompte_amount': 'مبلغ التسبيق المدفوع',
      'remaining_to_credit': 'المبلغ المسجل في الكريدي:',
      'credit_limit_exceeded': 'تحذير: هذا الزبون تجاوز سقف الدين المسموح به!',

      // Customers & Debts
      'total_credit_debts': 'إجمالي الديون المعلقة في المحل',
      'customers_count': 'زبون',
      'search_customer_hint': 'ابحث بالاسم أو برقم الهاتف...',
      'no_customers_found': 'لا يوجد زبائن مسجلين حالياً',
      'add_customer': 'إضافة زبون جديد',
      'add_customer_title': 'تسجيل زبون جديد في الكريدي',
      'customer_name': 'اسم الزبون الكامل',
      'customer_phone': 'رقم الهاتف',
      'customer_address': 'العنوان / الحي',
      'initial_debt': 'الدين الأولي (إن وجد)',
      'max_debt_limit': 'سقف الدين الأقصى (دج)',
      'current_debt': 'الدين الحالي المستحق',
      'total_debt_balance': 'رصيد الدين الكلي',
      'pay_debt': 'تسديد دين',
      'pay_debt_title': 'تسجيل تسديد دين',
      'paid_amount': 'المبلغ المدفوع (دج)',
      'payment_note': 'ملاحظة (اختياري)',
      'confirm_payment': 'تأكيد التسديد وطباعة الوصل',
      'payment_recorded_msg': 'تم تسجيل تسديد الدين بنجاح',
      'pay_now_btn': 'تسديد',
      'debt_transactions_history': 'سجل المعاملات والديون',
      'no_debt_history': 'لا توجد معاملات سابقة لهذا الزبون',
      'credit_purchase': 'شراء بالكريدي',
      'payment_received': 'تسديد دين',
      'enter_valid_amount': 'يرجى إدخال مبلغ صحيح',

      // Scale & Weighable (Vrac)
      'scale_calculator': 'حاسبة سلع الميزان والتجزئة (Vrac)',
      'add_weighable_item': 'إضافة مادة ميزان جديدة',
      'supply_method': 'طريقة التوريد والمخزون',
      'by_bags': 'بالأكياس / الشكاير',
      'by_direct_kg': 'بالكيلوغرام المباشر',
      'bags_count': 'عدد الشكاير',
      'bag_weight': 'وزن الشكارة (كغ)',
      'total_calculated_stock': 'المخزون المحسوب الكلي',
      'price_per_kg': 'سعر الكيلو (دج)',
      'cost_per_kg': 'سعر التكلفة للكيلو (دج)',
      'supplier_name': 'اسم المورد / شركة التوزيع',
      'weighable_stock': 'مخزون الميزان',

      // Quick Items Customization
      'edit_quick_item': 'تعديل السلعة السريعة',
      'add_quick_item': 'إضافة سلعة سريعة جديدة',
      'quick_item_price': 'سعر السلعة (دج)',
      'quick_item_name': 'اسم السلعة',
      'quick_item_icon': 'الأيقونة (إيموجي)',
      'price_updated_msg': 'تم تحديث السعر بنجاح ⚡',

      // Cost & Net Profit
      'cost_price': 'سعر الشراء (التكلفة)',
      'selling_price': 'سعر البيع',
      'net_profit': 'صافي الأرباح',
      'estimated_profit': 'صافي الربح التقديري',
      'profit_margin': 'نسبة هامش الربح',
      'total_cost': 'إجمالي تكلفة السلع',

      // Change Calculator
      'change_calc': 'حاسبة الصرف والباقي',
      'exact_amount': 'المضبوط',
      'change_due': 'الباقي للزبون (الصرف):',
      'insufficient_amount': 'المبلغ المدفوع أقل من الإجمالي المطلوب!',

      // Quick Add Bottom Sheet
      'quick_add_title': 'منتج غير مسجل - إضافة سريعة',
      'master_recognized': 'تم التعرف على المنتج في الكتالوج الجزائري! 🇩🇿',
      'barcode_label': 'باركود',
      'product_name': 'اسم المنتج',
      'initial_stock': 'الكمية الأولية',
      'save_and_add_cart': 'حفظ وإضافة للسلة',
      'saved_product_msg': 'تمت إضافة المنتج بنجاح إلى المخزون والسلة',

      // Stock In & Supplier Invoices
      'stock_in_title': 'استلام السلع / Arrivage',
      'stock_in_hint': 'امسح الباركود لزيادة المخزون فورياً',
      'supplier_invoices': 'فواتير الموردين والمشتريات',
      'new_supplier_invoice': 'فاتورة مورد جديدة',
      'settle_supplier_debt': 'تسديد دين للمورد',
      'total_purchases': 'إجمالي المشتريات',
      'remaining_debt': 'الدين المتبقي',

      // Expenses & Cashier Shifts
      'store_expenses': 'مصاريف ونفقات المحل',
      'record_expense': 'تسجيل مصروف',
      'today_expenses': 'مصاريف اليوم',
      'month_expenses': 'مصاريف الشهر',
      'cashier_shifts': 'مناوبات الكاسة والصندوق',
      'devis_proforma': 'عروض الأسعار والفواتير المبدئية',
      'receipt_designer': 'تخصيص وتصميم الوصل الحراري',
      'security_pin_title': 'رمز الأمان PIN للمالك 🔒',

      // Daily Report
      'daily_report_title': 'تقرير اليومية والمبيعات',
      'today_revenue': 'مداخيل اليومية الإجمالية',
      'invoices_count': 'عدد الفواتير',
      'sold_items_count': 'السلع المباعة',
      'today_invoices': 'فواتير اليوم المكتملة',
      'print_z_report': 'طباعة تقرير الإغلاق اليومي (Rapport Z)',
      'no_sales_today': 'لم يتم تسجيل أي مبيعات اليوم حتى الآن',

      // Products List
      'products_title': 'إدارة المنتجات والمخزون',
      'in_stock': 'متوفر',
      'low_stock': 'منخفض',
      'out_of_stock': 'نفد المخزون',
      'add_product': 'إضافة منتج جديد',
      'edit_product': 'تعديل المنتج',
      'export_excel': 'تصدير كملف Excel (CSV)',
      'exported_success': 'تم تصدير الملف بنجاح!',

      // HR, Staff & Payroll
      'hr_staff_management': 'إدارة الموظفين والموارد البشرية',
      'hr_payroll': 'كشوف الرواتب والأجور',
      'hr_advances': 'السلفيات والتسبيقات',
      'hr_base_salary': 'الراتب الأساسي',
      'hr_attendance_pointage': 'سجل الحضور والانصراف',
      'hr_department': 'القسم / الوظيفة',
      'pos_station_radar': 'رادار الكاشيرات الحية',
      'call_supervisor': 'نداء المشرف العام للمساعدة 🔔',
      'blind_shift_close': 'إغلاق الصندوق الأعمى',
      'cash_denominations': 'حاسبة الفئات النقدية الجزائرية 🇩🇿',
      'unique_pin_error': 'هذا الرمز السري مستخدم مسبقاً لعامل آخر!',

      // Product Edit & Details
      'edit_product_title': 'تعديل تفاصيل السلعة ✏️',
      'product_image': 'صورة المنتج 📸',
      'product_image_hint': 'تظهر بالتطبيق ولا تطبع على الوصل',
      'search_image_web': 'بحث صورة بالإنترنت 🌐',
      'camera': 'كاميرا 📷',
      'gallery': 'معرض 🖼️',
      'no_image': 'لا توجد صورة للمنتج',
      'remove_image': 'إزالة الصورة',
      'barcode_editable_hint': 'امسح أو اكتب الباركود...',
      'scan_camera': 'مسح باركود جديد بالكاميرا',
      'product_name_label': 'اسم السلعة / المنتج *',
      'category_label': 'قسم / صنف السلعة 📂',
      'unit_label': 'وحدة البيع والقياس 📏📦',
      'unit_piece': 'بالقطعة/علبة 📦',
      'unit_meter': 'بالمتر 📏',
      'unit_ml': 'بالمليلتر 🧴',
      'unit_weight': 'بالميزان (كغ) ⚖️',
      'multipack_title': 'إدارة تسعير الكراتين والعلب (Multi-Pack)',
      'multipack_subtitle': 'تفعيل بيع المنتج بالكرتونة أو بالعلبة، وتحديد عدد الوحدات',
      'carton_retail_price': 'سعر بيع الكرطوشة (تجزئة)',
      'carton_wholesale_price': 'سعر بيع الكرطوشة (جملة)',
      'pack_wholesale_price': 'سعر بيع العلبة (جملة)',
      'single_piece_price': 'سعر بيع السيجارة بالحبة (دج)',
      'pieces_per_pack': 'سجائر في العلبة',
      'packs_per_carton': 'علب في الكرطوشة',
      'sold_by_weight_title': 'تباع بالميزان (بالكيلوغرام) ⚖️',
      'sold_by_weight_hint': 'احتساب السعر حسب الوزن والكسور',
      'cost_price_input': 'سعر التكلفة (Achat)',
      'retail_price_input': 'سعر البيع (Détail) *',
      'wholesale_price_input': 'سعر الجملة (Gros)',
      'stock_quantity_label': 'الكمية الحالية في المخزون',
      'quick_arrivage_label': 'إضافة شحنة سريعة:',
      'expiry_date_label': 'تاريخ انتهاء الصلاحية (Péremption):',
      'no_expiry_date': 'لا يوجد تاريخ صلاحية محدد',
      'save_changes_btn': 'حفظ التعديلات 💾',
      'shelf_tag_btn': 'طباعة بطاقة الرف 🏷️',

      // Options Menu in Products List
      'quick_restock_menu': 'استلام شحنة جديدة 📦',
      'edit_product_menu': 'تعديل السلعة والأسعار ✏️',
      'shelf_label_menu': 'طباعة ملصق السعر 🏷️',
      'pin_to_quick_menu': 'تثبيت في البيع السريع ⚡',
      'delete_product_menu': 'حذف من المخزون 🗑️',
      'batch_actions_title': 'إجراءات مجمعة',
      'clear_selection': 'إلغاء التحديد ✖',

      // Universal DB Importer & Backup
      'browse_file_btn': 'تصفح واختيار ملف من القرص أو الفلاش ديسك 📁',
      'browse_folder_btn': 'فحص مجلد مخصص في قرص خارجي (USB) 🔍',
      'restore_db_title': 'استرجاع واستيراد قاعدة البيانات 📥',
      'restore_db_desc': 'يقبل جميع الصيغ (.nbak, .zip, .json, .csv, .txt) من أي برنامج سابق',
      'analysis_summary_title': 'معاينة وتحليل ملف البيانات 📊',
      'format_detected': 'الصيغة المكتشفة:',
      'products_detected': 'السلع المكتشفة:',
      'images_detected': 'الصور المكتشفة والمطابقة:',
      'invoices_detected': 'الفواتير المكتشفة:',
      'customers_detected': 'الزبائن المكتشفون:',
      'restore_mode_replace': 'استبدال شامل (مسح القديم وتثبيت الملف بالكامل)',
      'restore_mode_merge': 'دمج وإضافة ذكية (تحديث السلع وإضافة الجديد دون حذف)',
      'confirm_import_btn': 'بدء الاستيراد والاسترجاع 🚀',
      'restore_success_msg': '✅ تم استرجاع واستيراد قاعدة البيانات بنجاح!',
      'restore_failed_msg': '❌ تعذر استرجاع الملف، تأكد من سلامة البيانات',

      // Master Catalog Hub & Store Setup Wizard
      'master_catalog_title': 'مكتبة السلع الجزائرية الكبرى 🇩🇿',
      'master_catalog_subtitle': '100,000+ سلعة بالباركود والصور جاهزة للاستخدام فوراً',
      'auto_detect_pos_badge': 'التعرف التلقائي نشط في شاشة البيع ⚡',
      'setup_wizard_btn': 'معالج التجهيز السريع للمحل حسب النشاط 🚀',
      'browse_catalog_btn': 'تصفح والبحث في الكتالوج 🔍',
      'setup_wizard_title': 'تجهيز المتجر فوراً حسب النشاط 🏪',
      'setup_wizard_desc': 'اختر نشاط محلك لتنزيل السلع الأكثر مبيعاً مع صورها وأسعارها بضغطة زر',
      'act_superette': 'سوبرماركت وبقالة عامة (Superette)',
      'act_kiosk': 'كشك وتبغ وسجائر ومشروبات (Kiosque)',
      'act_cosmetics': 'مواد التجميل ومواد التنظيف (Hygiène)',
      'act_dairy': 'ألبان ومخبوزات ومصبرات (Épicerie)',
      'setup_store_now': 'تجهيز المتجر الآن',
      'store_setup_success': '🎉 تم تجهيز متجرك وإضافة السلع بنجاح!',
      'business_hubs_title': 'مراكز إدارة الأعمال والنشاط التجاري 🗂️',
      'custom_header_title': 'تخصيص ألوان الشريط والشعار',
      'custom_header_subtitle': 'اختر من الثيمات الجاهزة أو حدد لوناً مخصصاً لمتجرك',
      'preview_badge': 'معاينة حية',
      'color_presets_title': 'ثيمات وألوان مسبقة الإعداد:',
      'custom_palette_title': 'ألوان مخصصة:',
      'confirm_btn': 'تأكيد وحفظ',
      'theme_amoled_dark': 'الوضع الداكن AMOLED',
      'theme_light': 'الوضع الساطع',
      'tobacco_modal_title': 'قائمة المواد التبغية والسجائر 🚬',
      'tobacco_btn': 'مواد تبغية 🚬',
      'customize_toolbar_btn': 'ترتيب وتخصيص ⚙️',
      'switch_theme_tooltip': 'التبديل بين وضع Amoled والوضع الساطع',
      'color_palette_tooltip': 'تخصيص ألوان الشريط والشعار 🎨',
      'open_shifts_btn': 'الورديات (Z-Report)',
      'commercial_docs_btn': 'الوثائق التجارية',
      'backup_btn': 'النسخ الاحتياطي',
      'master_catalog_btn': 'كتالوج السلع (59K)',
      'products_hub_btn': 'المخزون والسلع',
      'reports_hub_btn': 'التقارير اليومية',
      'held_carts_btn': 'سلات معلقة (F6)',
      'quick_scale_btn': 'ميزان باركود',
      'sync_companion_btn': 'ربط الهاتف',
      'app_settings_btn': 'إعدادات النظام',
      'full_screen_btn': 'شاشة كاملة (F11)',
      'exit_app_btn': 'إغلاق البرنامج (Esc)',
      'single_cigarette': 'سيجارة فردية',
      'pack_unit': 'علبة / باكي',
      'carton_unit': 'خرطوشة / كرتوشة',
      'piece_unit': 'حبة / قطعة',
      'box_unit': 'صندوق / علبة',
      'retail_tier': 'سعر التجزئة',
      'semi_wholesale_tier': 'نصف جملة',
      'wholesale_tier': 'سعر الجملة',
      'cash_payment': 'دفع نقداً (Espèces)',
      'credit_payment': 'تسجيل على الحساب (Crédit)',
      'card_payment': 'بطاقة بنكية (Carte)',
      'cheque_payment': 'صك بنكي (Chèque)',
      'paid_amount_label': 'المبلغ المدفوع من الزبون',
      'change_due_label': 'المبلغ المتبقي للإرجاع للزبون',
      'supplier_invoice_title': 'فاتورة شراء واستلام شحنة جديدة',
      'stock_alert_title': 'تنبيهات انخفاض ونفاد المخزون',
      'losses_title': 'سجل التالف والخسائر',
      'expiry_title': 'مراقبة تواريخ الصلاحية',
      'shopping_list_title': 'قائمة المشتريات والنواقص',
      'shelf_labels_title': 'طباعة ملصقات الأسعار والرفوف',
    },
    'fr': {
      // General & Navigation
      'app_name': 'Nayli Kiosk Pro',
      'app_title': 'Nayli Kiosk - Caisse & Stock POS',
      'pos_welcome': '🌟 Bienvenue • Welcome',
      'pos_title': 'Système POS & Caisse Rapide',
      'cart': 'Panier',
      'items_count': 'Articles',
      'total_price': 'Total Général',
      'grand_total': 'Total Général',
      'checkout': 'Détails & Paiement',
      'review_order': 'Payer la commande',
      'settings': 'Paramètres',
      'products_management': 'Gestion des Produits & Stock',
      'stock_in': 'Réception / Arrivage',
      'daily_report': 'Rapport Journalier & Bénéfices',
      'shop_details': 'Informations Boutique',
      'credit_ledger': 'Carnet de Crédit (Dettes)',
      'credit_ledger_title': 'Gestion des Crédits Clients',
      'hardware': 'Matériel & Périphériques',
      'print_device': 'Imprimante Tickets',
      'connected': 'Connecté',
      'disconnected': 'Déconnecté',
      'language': 'Langue de l\'application',
      'arabic': 'العربية (AR)',
      'french': 'Français (FR)',
      'english': 'English (EN)',
      'close': 'Fermer',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'search': 'Recherche...',
      'required': 'Champ obligatoire',
      'balance': 'Solde',

      // POS, Scanner & Actions
      'camera_off': 'Caméra éteinte',
      'turn_on_camera': 'Allumer la caméra',
      'align_barcode': 'Alignez le code-barres dans le cadre',
      'cart_empty': 'Le panier est vide',
      'cart_empty_hint': 'Scannez un code-barres ou choisissez un article rapide ci-dessus',
      'clear_cart': 'Vider le panier',
      'clear_cart_confirm': 'Voulez-vous vraiment vider tout le panier et recommencer ?',
      'park_cart': 'Mettre en attente',
      'parked_cart_msg': 'Panier mis en attente ⏸️',
      'resume_cart': 'Reprendre le panier',
      'resumed_cart_msg': 'Panier récupéré ▶️',
      'held_carts': 'Paniers en attente',
      'return_mode': 'Mode Retour 🔄',
      'return_mode_active': 'Mode Retour Activé',
      'return_mode_hint': 'Les articles seront réintégrés au stock et remboursés',
      'discount': 'Remise',
      'apply_discount': 'Appliquer la remise',
      'remove_discount': 'Supprimer la remise',
      'stock_zero_warning': 'Stock: 0',
      'item_name': 'Article',
      'item_price': 'Prix',
      'total': 'Total',
      'quantity': 'Qté',
      'new_invoice': 'Nouveau Ticket',
      'confirm_and_print': 'Valider et Imprimer',
      'reprint': 'Réimprimer Ticket',
      'printed_success': '✅ Transaction enregistrée et ticket imprimé !',
      'tier_detail': 'Détail (F5)',
      'tier_demi_gros': 'Demi-Gros (F5)',
      'tier_gros': 'Gros (F5)',
      'scan_input_hint': 'Scannez le code-barres ou Qté*Code (F1)...',
      'table_product': 'Produit',
      'table_qty': 'Qté',
      'table_price': 'Prix',
      'table_total': 'Total',
      'cart_items_count': 'Nombre d\'articles',
      'cart_net_total': 'Total Net à Payer:',
      'btn_discount': 'Remise (F4)',
      'btn_hold': 'En Attente (F2)',
      'btn_pay_checkout': 'Payer & Encaisser (F12)',
      'pos_incoming_carts': 'Paniers Reçus',
      'pos_open_drawer': 'Ouvrir Tiroir (F10)',
      'pos_commercial_docs': 'Documents Commerciaux',
      'pos_backup_sync': 'Sauvegarde & Cloud',
      'pos_shifts_zreport': 'Sessions de Caisse (Rapport Z)',
      'pos_master_catalog': 'Catalogue Algérien (59K)',
      'pos_inventory': 'Stock & Produits',
      'pos_reports': 'Rapports Journaliers',
      'pos_settings': 'Paramètres & Matériel',
      'hotkeys_hint': '[F1: Scan]   [F2: Attente]   [F3: Client]   [F4: Remise]   [F5: Gros/Détail]   [F6: Retour]   [F7: Rapide]   [F8: Prix]   [F9: Paniers]   [F12: Payer]',

      // Categories
      'cat_all': 'Tous',
      'cat_stationery': 'Fournitures Scolaires',
      'cat_beverages': 'Boissons',
      'cat_pulses': 'Épicerie',
      'cat_cleaning': 'Entretien',
      'cat_sweets': 'Confiserie',
      'cat_scale': 'Vrac & Poids',
      'cat_dairy': 'Laitiers',
      'cat_spices': 'Épices',
      'cat_tobacco': 'Tabac & Cigarettes',

      // Payment & Credit Modes
      'payment_mode': 'Mode de Paiement',
      'pay_cash': 'Espèces (Cash)',
      'pay_credit': 'Crédit Complet',
      'pay_acompte': 'Acompte + Crédit',
      'select_customer': 'Sélectionner un Client',
      'select_customer_hint': 'Cliquez pour choisir le client à débiter',
      'acompte_amount': 'Montant de l\'acompte versé',
      'remaining_to_credit': 'Montant ajouté au crédit:',
      'credit_limit_exceeded': 'Attention : Le client a dépassé son plafond de crédit !',

      // Customers & Debts
      'total_credit_debts': 'Total des Dettes Clients en cours',
      'customers_count': 'clients',
      'search_customer_hint': 'Rechercher par nom ou numéro...',
      'no_customers_found': 'Aucun client enregistré',
      'add_customer': 'Ajouter un Client',
      'add_customer_title': 'Enregistrer un Nouveau Client',
      'customer_name': 'Nom complet du client',
      'customer_phone': 'Numéro de téléphone',
      'customer_address': 'Adresse / Quartier',
      'initial_debt': 'Dette initiale (si existante)',
      'max_debt_limit': 'Plafond max de crédit (DA)',
      'current_debt': 'Dette Actuelle',
      'total_debt_balance': 'Solde Global de Dette',
      'pay_debt': 'Versement Dette',
      'pay_debt_title': 'Enregistrer un Règlement de Dette',
      'paid_amount': 'Montant Versé (DA)',
      'payment_note': 'Note (Optionnel)',
      'confirm_payment': 'Confirmer & Imprimer Reçu',
      'payment_recorded_msg': 'Règlement enregistré avec succès',
      'pay_now_btn': 'Régler',
      'debt_transactions_history': 'Historique des Transactions',
      'no_debt_history': 'Aucun historique pour ce client',
      'credit_purchase': 'Achat à Crédit',
      'payment_received': 'Versement Dette',
      'enter_valid_amount': 'Veuillez saisir un montant valide',

      // Scale & Weighable (Vrac)
      'scale_calculator': 'Calculateur Balance & Vrac',
      'add_weighable_item': 'Ajouter un article de balance',
      'supply_method': 'Méthode d\'approvisionnement',
      'by_bags': 'Par sacs / cartons',
      'by_direct_kg': 'Au kilogramme direct',
      'bags_count': 'Nombre de sacs',
      'bag_weight': 'Poids du sac (kg)',
      'total_calculated_stock': 'Stock total calculé',
      'price_per_kg': 'Prix au kilo (DA)',
      'cost_per_kg': 'Prix de revient au kilo (DA)',
      'supplier_name': 'Nom du fournisseur',
      'weighable_stock': 'Stock Vrac',

      // Quick Items Customization
      'edit_quick_item': 'Modifier Article Rapide',
      'add_quick_item': 'Nouvel Article Rapide',
      'quick_item_price': 'Prix de l\'article (DA)',
      'quick_item_name': 'Nom de l\'article',
      'quick_item_icon': 'Icône (Émoji)',
      'price_updated_msg': 'Prix mis à jour avec succès ⚡',

      // Cost & Net Profit
      'cost_price': 'Prix d\'Achat (Coût)',
      'selling_price': 'Prix de Vente',
      'net_profit': 'Bénéfice Net',
      'estimated_profit': 'Bénéfice Net Estimé',
      'profit_margin': 'Marge Bénéficiaire',
      'total_cost': 'Coût Total des Ventes',

      // Change Calculator
      'change_calc': 'Calculateur de Monnaie',
      'exact_amount': 'Montant Exact',
      'change_due': 'Monnaie à rendre :',
      'insufficient_amount': 'Le montant donné est inférieur au total !',

      // Quick Add Bottom Sheet
      'quick_add_title': 'Produit non enregistré - Ajout rapide',
      'master_recognized': 'Reconnu dans le catalogue algérien ! 🇩🇿',
      'barcode_label': 'Code-barres',
      'product_name': 'Nom du produit',
      'initial_stock': 'Quantité initiale',
      'save_and_add_cart': 'Enregistrer et ajouter au panier',
      'saved_product_msg': 'Produit ajouté au stock et au panier',

      // Stock In & Supplier Invoices
      'stock_in_title': 'Réception / Arrivage',
      'stock_in_hint': 'Scannez le code-barres pour ajouter du stock',
      'supplier_invoices': 'Factures Fournisseurs',
      'new_supplier_invoice': 'Nouvelle Facture Fournisseur',
      'settle_supplier_debt': 'Régler Dette Fournisseur',
      'total_purchases': 'Achats Totaux',
      'remaining_debt': 'Dette Restante',

      // Expenses & Cashier Shifts
      'store_expenses': 'Dépenses & Charges du Magasin',
      'record_expense': 'Enregistrer une dépense',
      'today_expenses': 'Dépenses du jour',
      'month_expenses': 'Dépenses du mois',
      'cashier_shifts': 'Sessions de Caisse (Fond de caisse)',
      'devis_proforma': 'Devis & Pro-forma',
      'receipt_designer': 'Personnalisation du ticket',
      'security_pin_title': 'Code PIN Sécurité Propriétaire 🔒',

      // Daily Report
      'daily_report_title': 'Rapport Journalier des Ventes',
      'today_revenue': 'Recette Totale du Jour',
      'invoices_count': 'Nombre de Tickets',
      'sold_items_count': 'Articles Vendus',
      'today_invoices': 'Tickets Réalisés Aujourd\'hui',
      'print_z_report': 'Imprimer le Rapport Z',
      'no_sales_today': 'Aucune vente enregistrée pour le moment',

      // Products List
      'products_title': 'Gestion des Produits & Stock',
      'in_stock': 'En Stock',
      'low_stock': 'Stock Faible',
      'out_of_stock': 'Épuisé',
      'add_product': 'Ajouter un Produit',
      'edit_product': 'Modifier le Produit',
      'export_excel': 'Exporter vers Excel (CSV)',
      'exported_success': 'Exportation réussie !',

      // HR, Staff & Payroll
      'hr_staff_management': 'Gestion du Personnel & RH',
      'hr_payroll': 'Gestion de la Paie & Salaires',
      'hr_advances': 'Avances sur Salaire',
      'hr_base_salary': 'Salaire de Base',
      'hr_attendance_pointage': 'Pointage & Présence',
      'hr_department': 'Département / Poste',
      'pos_station_radar': 'Radar des Caisses en Direct',
      'call_supervisor': 'Appel Superviseur 🔔',
      'blind_shift_close': 'Clôture de Caisse à l\'Aveugle',
      'cash_denominations': 'Calculateur de Billets DZD',
      'unique_pin_error': 'Ce code PIN est déjà utilisé par un autre employé !',

      // Product Edit & Details
      'edit_product_title': 'Modifier le produit ✏️',
      'product_image': 'Photo du produit 📸',
      'product_image_hint': 'Visible dans l\'application, non imprimée sur ticket',
      'search_image_web': 'Recherche image en ligne 🌐',
      'camera': 'Caméra 📷',
      'gallery': 'Galerie 🖼️',
      'no_image': 'Aucune image de produit',
      'remove_image': 'Supprimer la photo',
      'barcode_editable_hint': 'Scanner ou taper le code-barres...',
      'scan_camera': 'Scanner avec la caméra',
      'product_name_label': 'Nom du produit *',
      'category_label': 'Catégorie / Rayon 📂',
      'unit_label': 'Unité de vente 📏📦',
      'unit_piece': 'À l\'unité / Pièce 📦',
      'unit_meter': 'Au mètre 📏',
      'unit_ml': 'Au millilitre 🧴',
      'unit_weight': 'Au poids (Kg) ⚖️',
      'multipack_title': 'Tarification Cartons & Paquets',
      'multipack_subtitle': 'Activer la vente au carton, paquet ou unité',
      'carton_retail_price': 'Prix carton (Détail)',
      'carton_wholesale_price': 'Prix carton (Gros)',
      'pack_wholesale_price': 'Prix paquet (Gros)',
      'single_piece_price': 'Prix cigarette à l\'unité',
      'pieces_per_pack': 'Cigarettes par paquet',
      'packs_per_carton': 'Paquets par carton',
      'sold_by_weight_title': 'Vente au kilo (Balance) ⚖️',
      'sold_by_weight_hint': 'Calcul du prix selon le poids pesé',
      'cost_price_input': 'Prix d\'achat (Coût)',
      'retail_price_input': 'Prix de vente (Détail) *',
      'wholesale_price_input': 'Prix de gros',
      'stock_quantity_label': 'Quantité actuelle en stock',
      'quick_arrivage_label': 'Ajout rapide au stock :',
      'expiry_date_label': 'Date de péremption :',
      'no_expiry_date': 'Aucune date de péremption',
      'save_changes_btn': 'Enregistrer les modifications 💾',
      'shelf_tag_btn': 'Imprimer étiquette rayon 🏷️',

      // Options Menu in Products List
      'quick_restock_menu': 'Arrivage rapide 📦',
      'edit_product_menu': 'Modifier l\'article ✏️',
      'shelf_label_menu': 'Imprimer étiquette 🏷️',
      'pin_to_quick_menu': 'Épingler en caisse ⚡',
      'delete_product_menu': 'Supprimer du stock 🗑️',
      'batch_actions_title': 'Actions groupées',
      'clear_selection': 'Désélectionner ✖',

      // Universal DB Importer & Backup
      'browse_file_btn': 'Parcourir et choisir un fichier 📁',
      'browse_folder_btn': 'Scanner un dossier externe (USB) 🔍',
      'restore_db_title': 'Restauration de la base de données 📥',
      'restore_db_desc': 'Supporte tous les formats (.nbak, .zip, .json, .csv, .txt)',
      'analysis_summary_title': 'Analyse du fichier de données 📊',
      'format_detected': 'Format détecté :',
      'products_detected': 'Produits détectés :',
      'images_detected': 'Images détectées :',
      'invoices_detected': 'Factures détectées :',
      'customers_detected': 'Clients détectés :',
      'restore_mode_replace': 'Remplacement complet (Écraser les données)',
      'restore_mode_merge': 'Fusion intelligente (Ajouter sans supprimer)',
      'confirm_import_btn': 'Lancer l\'importation 🚀',
      'restore_success_msg': '✅ Base de données restaurée avec succès !',
      'restore_failed_msg': '❌ Échec de la restauration, vérifiez le fichier',

      // Master Catalog Hub & Store Setup Wizard
      'master_catalog_title': 'Grand Catalogue Algérien 🇩🇿',
      'master_catalog_subtitle': '100 000+ articles avec codes-barres et photos prêts',
      'auto_detect_pos_badge': 'Détection auto active en caisse ⚡',
      'setup_wizard_btn': 'Assistant de configuration rapide 🚀',
      'browse_catalog_btn': 'Parcourir le catalogue 🔍',
      'setup_wizard_title': 'Configuration immédiate du magasin 🏪',
      'setup_wizard_desc': 'Choisissez votre activité pour charger les articles les plus vendus',
      'act_superette': 'Superette & Alimentation générale',
      'act_kiosk': 'Kiosque, Tabac & Boissons',
      'act_cosmetics': 'Cosmétique & Produits d\'entretien',
      'act_dairy': 'Laiterie, Pain & Conserves',
      'setup_store_now': 'Configurer maintenant',
      'store_setup_success': '🎉 Magasin configuré avec succès !',
      'business_hubs_title': 'Centres de gestion commerciale 🗂️',
    },
    'en': {
      // General & Navigation
      'app_name': 'Nayli Kiosk Pro',
      'app_title': 'Nayli Kiosk - Smart POS & Inventory Management',
      'pos_welcome': '🌟 Welcome • Bienvenue',
      'pos_title': 'Fast POS & Checkout System',
      'cart': 'Shopping Cart',
      'items_count': 'Items',
      'total_price': 'Grand Total',
      'grand_total': 'Grand Total',
      'checkout': 'Invoice Details & Payment',
      'review_order': 'Checkout Order',
      'settings': 'Settings & Preferences',
      'products_management': 'Products & Stock Management',
      'stock_in': 'Stock In / Arrivage',
      'daily_report': 'Daily Sales & Profit Report',
      'shop_details': 'Store Information',
      'credit_ledger': 'Customer Credit Ledger',
      'credit_ledger_title': 'Customer Credit & Debt Management',
      'hardware': 'Hardware & Devices',
      'print_device': 'Thermal Receipt Printer',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'language': 'Application Language',
      'arabic': 'العربية (AR)',
      'french': 'Français (FR)',
      'english': 'English (EN)',
      'close': 'Close',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search...',
      'required': 'This field is required',
      'balance': 'Balance',

      // POS, Scanner & Actions
      'camera_off': 'Camera is turned off',
      'turn_on_camera': 'Turn on camera',
      'align_barcode': 'Align barcode inside frame',
      'cart_empty': 'Cart is currently empty',
      'cart_empty_hint': 'Scan barcode with camera or tap quick item above',
      'clear_cart': 'Clear Cart',
      'clear_cart_confirm': 'Are you sure you want to clear all items in this cart and start fresh?',
      'park_cart': 'Hold Cart',
      'parked_cart_msg': 'Cart parked successfully ⏸️',
      'resume_cart': 'Resume Cart',
      'resumed_cart_msg': 'Held cart restored ▶️',
      'held_carts': 'Held Carts',
      'return_mode': 'Return & Refund Mode 🔄',
      'return_mode_active': 'Return Mode Active',
      'return_mode_hint': 'Items will be returned to stock and refunded to customer',
      'discount': 'Discount',
      'apply_discount': 'Apply Discount',
      'remove_discount': 'Remove Discount',
      'stock_zero_warning': 'Stock: 0',
      'item_name': 'Item Name',
      'item_price': 'Price',
      'total': 'Total',
      'quantity': 'Qty',
      'new_invoice': 'New Invoice',
      'confirm_and_print': 'Confirm & Print Receipt',
      'reprint': 'Reprint Receipt',
      'printed_success': '✅ Sale recorded, stock adjusted and receipt printed!',
      'tier_detail': 'Retail (F5)',
      'tier_demi_gros': 'Semi-Wholesale (F5)',
      'tier_gros': 'Wholesale (F5)',
      'scan_input_hint': 'Scan barcode or Qty*Code (F1)...',
      'table_product': 'Product',
      'table_qty': 'Qty',
      'table_price': 'Price',
      'table_total': 'Total',
      'cart_items_count': 'Items Count',
      'cart_net_total': 'Net Total Due:',
      'btn_discount': 'Discount (F4)',
      'btn_hold': 'Hold (F2)',
      'btn_pay_checkout': 'Pay & Checkout (F12)',
      'pos_incoming_carts': 'Incoming Carts',
      'pos_open_drawer': 'Open Drawer (F10)',
      'pos_commercial_docs': 'Commercial Documents',
      'pos_backup_sync': 'Backup & Cloud Sync',
      'pos_shifts_zreport': 'Cashier Shifts (Z-Report)',
      'pos_master_catalog': 'Algerian Catalog (59K)',
      'pos_inventory': 'Inventory & Products',
      'pos_reports': 'Daily Reports',
      'pos_settings': 'Settings & Hardware',
      'hotkeys_hint': '[F1: Scan]   [F2: Hold]   [F3: Customer]   [F4: Discount]   [F5: Wholesale]   [F6: Return]   [F7: Quick]   [F8: Price]   [F9: Incoming]   [F12: Pay]',

      // Categories
      'cat_all': 'All',
      'cat_stationery': 'Stationery',
      'cat_beverages': 'Beverages',
      'cat_pulses': 'Grocery',
      'cat_cleaning': 'Cleaning',
      'cat_sweets': 'Sweets',
      'cat_scale': 'Scale & Bulk',
      'cat_dairy': 'Dairy',
      'cat_spices': 'Spices',
      'cat_tobacco': 'Tobacco & Cigarettes',

      // Payment & Credit Modes
      'payment_mode': 'Payment Method',
      'pay_cash': 'Cash',
      'pay_credit': 'Full Credit (Debt)',
      'pay_acompte': 'Deposit + Credit',
      'select_customer': 'Select Customer',
      'select_customer_hint': 'Tap to select customer for credit record',
      'acompte_amount': 'Deposit Paid Amount',
      'remaining_to_credit': 'Remaining Debt Added:',
      'credit_limit_exceeded': 'Warning: Customer exceeded maximum debt limit!',

      // Customers & Debts
      'total_credit_debts': 'Total Customer Debts in Store',
      'customers_count': 'customers',
      'search_customer_hint': 'Search by name or phone...',
      'no_customers_found': 'No customers registered yet',
      'add_customer': 'Add New Customer',
      'add_customer_title': 'Register New Customer in Credit Book',
      'customer_name': 'Customer Full Name',
      'customer_phone': 'Phone Number',
      'customer_address': 'Address / City',
      'initial_debt': 'Initial Debt (if any)',
      'max_debt_limit': 'Max Debt Limit (DA)',
      'current_debt': 'Current Debt',
      'total_debt_balance': 'Total Debt Balance',
      'pay_debt': 'Pay Debt',
      'pay_debt_title': 'Record Debt Payment',
      'paid_amount': 'Paid Amount (DA)',
      'payment_note': 'Note (Optional)',
      'confirm_payment': 'Confirm & Print Receipt',
      'payment_recorded_msg': 'Debt payment recorded successfully',
      'pay_now_btn': 'Pay',
      'debt_transactions_history': 'Transaction History',
      'no_debt_history': 'No history for this customer',
      'credit_purchase': 'Credit Purchase',
      'payment_received': 'Debt Payment',
      'enter_valid_amount': 'Please enter a valid amount',

      // Scale & Weighable (Vrac)
      'scale_calculator': 'Weighing Scale & Bulk Calculator',
      'add_weighable_item': 'Add New Weighable Item',
      'supply_method': 'Supply Method & Stock',
      'by_bags': 'By Bags / Sacks',
      'by_direct_kg': 'Direct Kilograms',
      'bags_count': 'Bags Count',
      'bag_weight': 'Bag Weight (kg)',
      'total_calculated_stock': 'Total Calculated Stock',
      'price_per_kg': 'Price per Kg (DA)',
      'cost_per_kg': 'Cost per Kg (DA)',
      'supplier_name': 'Supplier Name',
      'weighable_stock': 'Weighable Stock',

      // Quick Items Customization
      'edit_quick_item': 'Edit Quick Item',
      'add_quick_item': 'Add New Quick Item',
      'quick_item_price': 'Item Price (DA)',
      'quick_item_name': 'Item Name',
      'quick_item_icon': 'Icon (Emoji)',
      'price_updated_msg': 'Price updated successfully ⚡',

      // Cost & Net Profit
      'cost_price': 'Cost Price (Purchase)',
      'selling_price': 'Selling Price',
      'net_profit': 'Net Profit',
      'estimated_profit': 'Estimated Net Profit',
      'profit_margin': 'Profit Margin',
      'total_cost': 'Total Cost of Sold Goods',

      // Change Calculator
      'change_calc': 'Change Calculator',
      'exact_amount': 'Exact',
      'change_due': 'Change Due:',
      'insufficient_amount': 'Paid amount is less than total!',

      // Quick Add Bottom Sheet
      'quick_add_title': 'Unregistered Product - Quick Add',
      'master_recognized': 'Recognized from Algerian Master Catalog! 🇩🇿',
      'barcode_label': 'Barcode',
      'product_name': 'Product Name',
      'initial_stock': 'Initial Stock',
      'save_and_add_cart': 'Save and Add to Cart',
      'saved_product_msg': 'Product saved successfully to inventory',

      // Stock In & Supplier Invoices
      'stock_in_title': 'Stock In / Arrivage',
      'stock_in_hint': 'Scan barcode to add new stock instantly',
      'supplier_invoices': 'Supplier Invoices & Purchases',
      'new_supplier_invoice': 'New Supplier Invoice',
      'settle_supplier_debt': 'Settle Supplier Debt',
      'total_purchases': 'Total Purchases',
      'remaining_debt': 'Remaining Debt',

      // Expenses & Cashier Shifts
      'store_expenses': 'Store Expenses & Utilities',
      'record_expense': 'Record Expense',
      'today_expenses': 'Today\'s Expenses',
      'month_expenses': 'Monthly Expenses',
      'cashier_shifts': 'Cashier Shifts (Cash Drawer)',
      'devis_proforma': 'Estimates & Quotations (Devis)',
      'receipt_designer': 'Thermal Receipt Designer',
      'security_pin_title': 'Owner Security PIN 🔒',

      // Daily Report
      'daily_report_title': 'Daily Sales Report',
      'today_revenue': 'Today\'s Total Revenue',
      'invoices_count': 'Invoices Count',
      'sold_items_count': 'Sold Items',
      'today_invoices': 'Today\'s Completed Invoices',
      'print_z_report': 'Print Z-Closing Report',
      'no_sales_today': 'No sales recorded today yet',

      // Products List
      'products_title': 'Product & Stock Management',
      'in_stock': 'In Stock',
      'low_stock': 'Low Stock',
      'out_of_stock': 'Out of Stock',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'export_excel': 'Export to Excel (CSV)',
      'exported_success': 'Exported successfully!',

      // HR, Staff & Payroll
      'hr_staff_management': 'Staff & HR Management',
      'hr_payroll': 'Payroll & Compensation',
      'hr_advances': 'Salary Advances',
      'hr_base_salary': 'Base Salary',
      'hr_attendance_pointage': 'Attendance Tracking',
      'hr_department': 'Department / Role',
      'pos_station_radar': 'Live Registers Radar',
      'call_supervisor': 'Call Supervisor 🔔',
      'blind_shift_close': 'Blind Shift Close',
      'cash_denominations': 'Cash Denomination Calculator',
      'unique_pin_error': 'This PIN is already used by another employee!',

      // Product Edit & Details
      'edit_product_title': 'Edit Product Details ✏️',
      'product_image': 'Product Photo 📸',
      'product_image_hint': 'Visible in app only, not printed on receipt',
      'search_image_web': 'Search Image Online 🌐',
      'camera': 'Camera 📷',
      'gallery': 'Gallery 🖼️',
      'no_image': 'No product image',
      'remove_image': 'Remove photo',
      'barcode_editable_hint': 'Scan or type barcode...',
      'scan_camera': 'Scan with camera',
      'product_name_label': 'Product Name *',
      'category_label': 'Category / Department 📂',
      'unit_label': 'Sales Unit 📏📦',
      'unit_piece': 'By Piece / Pack 📦',
      'unit_meter': 'By Meter 📏',
      'unit_ml': 'By Milliliter 🧴',
      'unit_weight': 'By Weight (Kg) ⚖️',
      'multipack_title': 'Cartons & Multi-Pack Pricing',
      'multipack_subtitle': 'Sell by carton, box, or single pieces',
      'carton_retail_price': 'Carton Price (Retail)',
      'carton_wholesale_price': 'Carton Price (Wholesale)',
      'pack_wholesale_price': 'Pack Price (Wholesale)',
      'single_piece_price': 'Single Piece / Cigarette Price',
      'pieces_per_pack': 'Pieces per pack',
      'packs_per_carton': 'Packs per carton',
      'sold_by_weight_title': 'Sold by weight (Scale) ⚖️',
      'sold_by_weight_hint': 'Price calculated from scale weight',
      'cost_price_input': 'Cost Price (Achat)',
      'retail_price_input': 'Retail Price (Détail) *',
      'wholesale_price_input': 'Wholesale Price (Gros)',
      'stock_quantity_label': 'Current Stock Quantity',
      'quick_arrivage_label': 'Quick stock addition:',
      'expiry_date_label': 'Expiry Date (Péremption):',
      'no_expiry_date': 'No expiry date set',
      'save_changes_btn': 'Save Changes 💾',
      'shelf_tag_btn': 'Print Shelf Tag 🏷️',

      // Options Menu in Products List
      'quick_restock_menu': 'Quick Restock 📦',
      'edit_product_menu': 'Edit Product ✏️',
      'shelf_label_menu': 'Print Shelf Label 🏷️',
      'pin_to_quick_menu': 'Pin to Quick Sale ⚡',
      'delete_product_menu': 'Delete from Stock 🗑️',
      'batch_actions_title': 'Batch Actions',
      'clear_selection': 'Clear Selection ✖',

      // Universal DB Importer & Backup
      'browse_file_btn': 'Browse & Choose File from Drive/USB 📁',
      'browse_folder_btn': 'Scan External Folder (USB) 🔍',
      'restore_db_title': 'Database Restore & Migration 📥',
      'restore_db_desc': 'Supports all formats (.nbak, .zip, .json, .csv, .txt)',
      'analysis_summary_title': 'Data File Analysis & Preview 📊',
      'format_detected': 'Detected Format:',
      'products_detected': 'Detected Products:',
      'images_detected': 'Detected Images:',
      'invoices_detected': 'Detected Invoices:',
      'customers_detected': 'Detected Customers:',
      'restore_mode_replace': 'Full Overwrite (Erase old data & restore)',
      'restore_mode_merge': 'Smart Merge (Update & add without erasing)',
      'confirm_import_btn': 'Start Import & Restore 🚀',
      'restore_success_msg': '✅ Database restored and imported successfully!',
      'restore_failed_msg': '❌ Restore failed, please verify the file format',

      // Master Catalog Hub & Store Setup Wizard
      'master_catalog_title': 'Master Algerian Catalog 🇩🇿',
      'master_catalog_subtitle': '100,000+ items with barcodes & photos ready to use',
      'auto_detect_pos_badge': 'Auto-detect active at POS ⚡',
      'setup_wizard_btn': 'Quick Store Setup Wizard 🚀',
      'browse_catalog_btn': 'Browse Catalog 🔍',
      'setup_wizard_title': 'Instant Store Setup by Activity 🏪',
      'setup_wizard_desc': 'Choose your activity to populate best-selling items in seconds',
      'act_superette': 'Supermarket & Grocery (Superette)',
      'act_kiosk': 'Kiosk, Tobacco & Drinks (Kiosque)',
      'act_cosmetics': 'Cosmetics & Hygiene (Hygiène)',
      'act_dairy': 'Dairy, Bread & Groceries (Épicerie)',
      'setup_store_now': 'Setup Store Now',
      'store_setup_success': '🎉 Store setup completed successfully!',
      'business_hubs_title': 'Business Management Hubs 🗂️',
      'custom_header_title': 'Customize Header & Logo',
      'custom_header_subtitle': 'Choose from presets or pick a custom theme',
      'preview_badge': 'Live Preview',
      'color_presets_title': 'Preset Themes:',
      'custom_palette_title': 'Custom Colors:',
      'confirm_btn': 'Confirm & Save',
      'theme_amoled_dark': 'AMOLED Dark Mode',
      'theme_light': 'Light Mode',
      'tobacco_modal_title': 'Tobacco & Cigarettes 🚬',
      'tobacco_btn': 'Tobacco 🚬',
      'customize_toolbar_btn': 'Customize ⚙️',
      'switch_theme_tooltip': 'Toggle Dark / Light Mode',
      'color_palette_tooltip': 'Customize Header Colors 🎨',
      'open_shifts_btn': 'Shifts (Z-Report)',
      'commercial_docs_btn': 'Commercial Documents',
      'backup_btn': 'Backup & Sync',
      'master_catalog_btn': 'Master Catalog (59K)',
      'products_hub_btn': 'Inventory & Products',
      'reports_hub_btn': 'Daily Reports',
      'held_carts_btn': 'Held Carts (F6)',
      'quick_scale_btn': 'Barcode Scale',
      'sync_companion_btn': 'Pair Phone',
      'app_settings_btn': 'System Settings',
      'full_screen_btn': 'Full Screen (F11)',
      'exit_app_btn': 'Exit (Esc)',
      'single_cigarette': 'Single Cigarette',
      'pack_unit': 'Pack',
      'carton_unit': 'Carton',
      'piece_unit': 'Piece',
      'box_unit': 'Box',
      'retail_tier': 'Retail Price',
      'semi_wholesale_tier': 'Semi-wholesale Price',
      'wholesale_tier': 'Wholesale Price',
      'cash_payment': 'Cash Payment',
      'credit_payment': 'Credit Account',
      'card_payment': 'Bank Card',
      'cheque_payment': 'Bank Cheque',
      'paid_amount_label': 'Paid Amount by Customer',
      'change_due_label': 'Change Due to Customer',
      'supplier_invoice_title': 'Purchase Invoice / Receipt',
      'stock_alert_title': 'Low Stock & Out of Stock Alerts',
      'losses_title': 'Losses & Damages Log',
      'expiry_title': 'Expiry Dates Tracker',
      'shopping_list_title': 'Shopping & Restock List',
      'shelf_labels_title': 'Shelf & Price Labels',
    },
  };


  // Direct Phrase Mapping Dictionary for Universal Auto-Translation
  static final Map<String, Map<String, String>> _phraseDictionary = {
    'fr': {
      'تطبيق': 'Appliquer',
      'تحديث': 'Actualiser',
      'طباعة': 'Imprimer',
      'مشاركة': 'Partager',
      'تصدير': 'Exporter',
      'عرض': 'Afficher',
      'اختيار': 'Sélectionner',
      'تفعيل': 'Activer',
      'تعطيل': 'Désactiver',
      'تم': 'Terminé',
      'إعدادات المتجر والشعار': 'Profil du Magasin & Logo',
      'تخصيص اسم المحل، العنوان، ورقم الهاتف على الوصل': 'Nom du magasin, adresse et téléphone sur le ticket',
      'طابعة الإيصالات الحرارية (Receipt)': 'Imprimante Reçus Thermique (Ticket)',
      'طابعة الباركود والملصقات (Sticker)': 'Imprimante Étiquettes Barcode',
      'إعداد طابعة ملصقات الأرفف والباركود الحرارية': 'Configurer l\'imprimante d\'étiquettes code-barres',
      'قارئ الباركود (Douchette / Scanner)': 'Lecteur Code-barres (Douchette)',
      'إعدادات قارئ الباركود السلكي أو اللاسلكي': 'Configuration du scanner filaire ou sans-fil',
      'الميزان الإلكتروني (Electronic Scale)': 'Balance Électronique',
      'ربط الميزان الإلكتروني لقراءة الوزن التلقائي': 'Connexion de la balance pour pesée automatique',
      'شاشة الزبون المنفصلة (Customer Display)': 'Afficheur Client',
      'عرض الحساب والأسعار للزبون على شاشة ثانية': 'Afficher les prix au client sur 2ème écran',
      'قفل النظام برمز PIN': 'Verrouillage par code PIN',
      'حماية الحسابات والأرباح برمز سري': 'Sécuriser la compta et les bénéfices par code',
      'النسخ الاحتياطي السحابي والمحلي': 'Sauvegarde Cloud & Locale',
      'حفظ قاعدة البيانات تلقائياً وتفادي ضياع البيانات': 'Sauvegarder la base de données sans risque',
      'استعادة نسخة سابقة': 'Restaurer une sauvegarde',
      'استرجاع قاعدة البيانات من ملف خارجي': 'Restaurer la base depuis un fichier',
      'تصدير المخزون إلى Excel': 'Exporter le stock vers Excel',
      'حفظ قائمة السلع والأسعار في ملف Excel': 'Sauvegarder articles et prix en Excel',
      'أصوات الكاشير والنغمات': 'Sons & Bips de Caisse',
      'تفعيل أصوات المسح والنجاح والتحذير': 'Bips de scan, succès et alertes sonores',
      'الإشعارات وتنبيهات المخزون': 'Notifications & Alertes de Stock',
      'تنبيه عند انخفاض المخزون وقرب انتهاء الصلاحية': 'Alerte stock faible et dates de péremption',
      'لغة التطبيق (Language)': 'Langue de l\'application',
      'النسخة مفعلة بالكامل': 'Version Activée Complète',
      'تفعيل النسخة الرسمية': 'Activer la Licence Officielle',
      'الترخيص نشط ويعمل على هذا الجهاز': 'Licence active sur cet appareil',
      'اضغط لإدخال كود التفعيل': 'Cliquez pour entrer le code d\'activation',
      'تفعيل برنامج الحاسوب بقارئ الباركود (Douchette) 🔫 📲': 'Activer le PC par scanner de code-barres 🔫 📲',
      'عرض رمز الاستجابة السريعة لتفعيل حاسوب الكاشير فوراً عبر الماسح': 'Afficher le QR code pour activer le PC de caisse',
      'عن التطبيق والإصدار': 'À propos de l\'application',
      'مركز المالية والتقارير والأرباح 📊': 'Hub Finances, Rapports & Bénéfices 📊',
      'الداشبورد والتقارير اليومية والأرباح': 'Dashboard, Rapports Quotidiens & Bénéfices',
      'صافي الأرباح، الإيرادات، ومبيعات اليوم (Z-Report)': 'Bénéfice net, recettes et ventes du jour (Z-Report)',
      'مصاريف ونفقات المحل': 'Dépenses & Frais du Magasin',
      'تسجيل فواتير الكهرباء، الكراء، ومصاريف العمال': 'Enregistrement électricité, loyer et charges',
      'مناوبات الكاسة والصندوق (Shifts)': 'Gestion des Shifts & Caisse',
      'رصيد البداية والختام وتسليم عهدة الصندوق بين العمال': 'Fond de caisse début/fin et passation',
      'مركز الوثائق والفواتير الشامل (Devis, BL, Factures) 📑': 'Facturation & Documents (Devis, BL, Factures) 📑',
      'عروض أسعار، وصولات تسليم، فواتير رسمية، وصولات قبض، وأرشفة': 'Devis, bons de livraison, factures et archivage',
      'مركز المخزون والسلع والتوالف 📦': 'Hub Stock, Articles & Pertes 📦',
      'إدارة المنتجات والأسعار': 'Gestion des Produits & Tarifs',
      'إضافة، تعديل الأسعار، ومراقبة الكميات': 'Ajout, modification des prix et contrôle du stock',
      'استلام السلع والشحنات (Arrivage)': 'Réception de Marchandises (Arrivage)',
      'مسح سريع وإدخال دفعات السلع الجديدة للمخزن': 'Scan rapide et entrée de stock nouveaux arrivages',
      'كتالوج السلع الجزائرية (100,000+)': 'Catalogue Produits Algériens (100 000+)',
      'تصفح واستيراد سلع السوبرماركت لمخزونك بضغطة زر': 'Importer les articles supermarché en 1 clic',
      'وحدة الجرد السنوي والدوري ورأس المال 📋⚖️': 'Inventaire Périodique & Capital 📋⚖️',
      'جرد المخزون بالكاميرا، حساب الفوارق، ورأس مال المحل': 'Inventaire caméra, écarts et valeur du stock',
      'سجل التوالف والكسر والاهتلاك 🗑️📉': 'Registre Casse & Pertes 🗑️📉',
      'شطب السلع المكسورة والتالفة وخصمها من المخزون وحساب الخسائر': 'Sortie des articles cassés et calcul des pertes',
      'مراقبة الصلاحية والتواريخ ⏳🚨': 'Suivi des Dates de Péremption ⏳🚨',
      'تتبع السلع القريبة من نهاية الصلاحية وتجنب الخسائر': 'Alerte produits proches de la péremption',
      'قائمة النواقص والتسوق (Shopping List) 🛒📝': 'Liste d\'Achats & Manquants 🛒📝',
      'سجل النواقص للشراء من سوق الجملة وتصديره ومشاركته': 'Liste des produits manquants pour achat en gros',
      'مركز العلاقات والديون والموردين 👥': 'Hub Clients, Dettes & Fournisseurs 👥',
      'دفتر ديون الزبائن (Crédit)': 'Carnet de Crédit Clients',
      'متابعة الديون، التسديدات، وسجل المعاملات والواتساب': 'Suivi des crédits, versements et rappels WhatsApp',
      'فواتير الموردين ومشتريات الجملة': 'Factures Fournisseurs & Achats Gros',
      'تسجيل فواتير الشراء، متابعة الديون، ودفعات الموردين': 'Achats fournisseurs, dettes et règlements',
      'عروض الأسعار والفواتير المبدئية (Devis)': 'Devis & Proformas',
      'إنشاء Devis رسمي وتحويله لفاتورة بيع بضغطة زر': 'Créer un devis et convertir en facture en 1 clic',
      'تأكيد وطباعة الوصل': 'Valider et imprimer',
      'طباعة وصل الكاشير:': 'Impression ticket de caisse :',
      'تغيير الطابعة': 'Changer d\'imprimante',
      'واتساب': 'WhatsApp',
      'تم تعطيل الطباعة الورقية (تسجيل البيع في النظام فقط)': 'Impression papier désactivée (vente enregistrée)',
      'الطابعة': 'Imprimante',
      'لم تحدد طابعة إيصالات (انقر لتحديدها)': 'Aucune imprimante sélectionnée',
      'لم يتم تحديد طابعة إيصالات': 'Aucune imprimante sélectionnée',
      'لم يتم اختيار طابعة الوصولات الحرارية.
هل ترغب في تسجيل البيع في النظام بدون طباعة ورقية لتفادي الطباعة على الطابعة الكبيرة؟': 'Aucune imprimante ticket sélectionnée.
Voulez-vous enregistrer la vente sans ticket papier ?',
      'نعم، حفظ بدون طباعة': 'Oui, sans impression',
      'تجاوز سقف الدين': 'Dépassement plafond de crédit',
      'إفراغ السلة الحالية': 'Vider le panier actuel',
      'هل أنت متأكد من حذف جميع السلع الممسوحة في هذه السلة والبدء من جديد؟': 'Voulez-vous vraiment vider tous les articles du panier ?',
      'تأكيد الإفراغ': 'Confirmer la suppression',
      'تعليق السلة الحالية (Panier en attente)': 'Mettre le panier en attente',
      'سيتم حفظ سلة هذا الزبون مؤقتاً لخدمة زبون آخر، ويمكنك استرجاعها في أي وقت خلال 20 دقيقة.': 'Ce panier sera conservé temporairement pour servir un autre client.',
      'تعليق الفاتورة': 'Mettre en attente',
      'تطبيق تخفيض / Remise': 'Appliquer une remise',
      'نسبة مئوية %': 'Pourcentage %',
      'المجموع بعد التخفيض:': 'Total après remise :',
      'إلغاء التخفيض': 'Annuler la remise',
      'شريط البيع السريع': 'Barre de vente rapide',
      'إضافة سلعة لشريط البيع السريع ⚡': 'Ajouter à la barre rapide ⚡',
      'تثبيت من المخزون': 'Épingler du stock',
      'سلعة مخصصة جديدة': 'Nouvel article libre',
      'ابحث عن سلعة في المخزون...': 'Rechercher un article du stock...',
      'لا توجد سلع في المخزون تطابق البحث': 'Aucun article correspondant trouvé',
      'تثبيت ⚡': 'Épingler ⚡',
      'تعديل السلعة السريعة': 'Modifier l\'article rapide',
      'حفظ التعديل': 'Sauvegarder',
      'ميزان وتجزئة (Vrac)': 'Balance & Vrac',
      'مبلغ مباشر (دايركت)': 'Montant direct',
      'وضع الإرجاع مفعّل 🔄': 'Mode Retour Activé 🔄',
      'إرسال السلة للكاشير الرئيسي 📤': 'Transférer au caissier principal 📤',
      'المسح المتعدد مفعّل': 'Scan multiple actif',
      'المسح العادي': 'Scan standard',
      'تشغيل/إيقاف الفلاش': 'Lampe torche On/Off',
      'تشغيل/إيقاف الكاميرا': 'Caméra On/Off',
      'سلع قريبة من النفاد': 'Articles proches de l\'épuisement',
      'قاربت الصلاحية ⏳': 'Date proche ⏳',
      'مخزون منخفض': 'Stock faible',
      'قائمة النواقص 🛒': 'Liste manquants 🛒',
      'كامل المخزن': 'Tout le stock',
      'د.ج': 'DA',
      'DA': 'DA',
      'غ': 'g',
      'مل': 'ml',
      'م': 'm',
      'حبات': 'pièces',
      'قطعة': 'pièce',
      'قطع': 'pièces',
      'علب': 'boîtes',
      'باكي': 'paquet',
      'كرطوشة': 'cartouche',
      'سجائر': 'cigarettes',
      'سجائر 🚬': 'cigarettes 🚬',
      'الميزان الذكي والسلع الحرة بدون باركود': 'Balance Intelligente & Vente au Vrac',
      'الوزن الصافي': 'Poids net',
      'سعر الكيلوغرام': 'Prix au kilo',
      'إضافة إلى السلة': 'Ajouter au panier',
      'تصفير الميزان': 'Tarer la balance',
      'السلع الحرة': 'Articles libres',
      'أدخل الوزن يدوياً': 'Entrer le poids manuellement',
      'زبون عابر (Détail)': 'Client de passage (Détail)',
      'تم حذفه من السلة': 'supprimé du panier',
      'سلة محولة من زميلك': 'Panier transféré de',
      'تذكرة': 'Ticket',
      'المبلغ': 'Montant',
      'تحتوي على سلع': 'Contient des articles',
      'قام زميلك بتحويل هذه السلة لتخليص الزبون بسبب نفاد الصرف لديه.': 'Votre collègue a transféré ce panier pour finaliser la commande.',
      'تأجيل في القائمة (F9)': 'Mettre en attente (F9)',
      'فتح السلة والمحاسبة الآن': 'Encaisser maintenant',
      'تم استلام السلة بنجاح!': 'Panier reçu avec succès !',
      'السلة فارغة! لا توجد سلع لتحويلها.': 'Le panier est vide !',
      'تحويل السلة لكاشير آخر 🔀': 'Transférer le panier à un collègue 🔀',
      'السلة الحالية': 'Panier actuel',
      'أدخل عنوان IP لجهاز الكاشير الثاني في الشبكة المحلية:': 'Entrez l\'IP du second caissier sur le réseau local :',
      'عنوان IP لجهاز الزميل (Peer IP)': 'Adresse IP du collègue (Peer IP)',
      'كاشير': 'Caisse',
      'تحويل السلة لزميلك الآن': 'Transférer le panier maintenant',
      'تم تحويل السلة بنجاح إلى كاشير!': 'Panier transféré avec succès au caissier !',
      'تعذر إرسال السلة. تأكد من تشغيل البرنامج لدى زميلك.': 'Échec du transfert. Vérifiez l\'application chez votre collègue.',
      'إرسال الوصل الرقمي عبر WhatsApp 💬': 'Envoyer le reçu numérique par WhatsApp 💬',
      'رقم هاتف الزبون (الجزائر)': 'N° de téléphone client',
      'إرسال الآن': 'Envoyer maintenant',
      'رقم الهاتف غير صالح!': 'Numéro de téléphone non valide !',
      'تم فتح تطبيق WhatsApp وإرسال الوصل!': 'WhatsApp ouvert et reçu envoyé !',
      'تعذر فتح WhatsApp، تم نسخ نص الوصل إلى الحافظة تلقائياً': 'Reçu copié dans le presse-papier',
      'تم تعليق السلة بنجاح وحفظها مؤقتاً (F2)': 'Panier mis en attente avec succès (F2)',
      'منتجات صنف': 'Produits de la catégorie',
      'انقر على أي منتج لإضافته مباشرة إلى السلة الحالية': 'Cliquez sur un article pour l\'ajouter au panier',
      'بحث في هذا الصنف بالاسم أو الباركود...': 'Rechercher par nom ou code...',
      'لا توجد منتجات مسجلة في صنف': 'Aucun produit enregistré dans',
      'تمت إضافته للسلة': 'ajouté au panier',
      'مخزون': 'Stock',
      'لوحة الأرقام اللمسية (Touch Numpad)': 'Pavé numérique tactile',
      'تحويل (F11)': 'Transférer (F11)',
      '+ إضافة منتج سريع': '+ Ajouter un article rapide',
      'سلعة حرة بدون باركود (F7)': 'Article libre sans code (F7)',
      'سريع ⚡': 'Rapide ⚡',
      'نسبة %': 'Pourcentage %',
      'مبلغ د.ج': 'Montant DA',
      'نسبة الخصم (%)': 'Taux de remise (%)',
      'مبلغ الخصم (DA)': 'Montant de remise (DA)',
      'الإعدادات والإدارة الشاملة ⚙️': 'Paramètres & Gestion Complète ⚙️',
      'الأجهزة والطباعة الحرارية 🖨️': 'Matériel & Impression Thermique 🖨️',
      'الأصوات والإشعارات والتنبيهات 🔊🔔': 'Sons, Notifications & Alertes 🔊🔔',
      'الأمان والنسخ الاحتياطي 🔒💾': 'Sécurité & Sauvegardes 🔒💾',
      'اللغة ومعلومات التطبيق 🌐✨': 'Langue & Infos de l\'Application 🌐✨',
      'المظهر والسمات (Thème & Apparence) 🎨🌙': 'Thème & Apparence Visuelle 🎨🌙',
      'وضع الشاشة الداكن الفائق (AMOLED Black)': 'Mode Sombre Profond (AMOLED Black)',
      'سواد خالص مريح للعين وموفر لاستهلاك الطاقة': 'Noir pur économique en énergie et reposant pour les yeux',
      'ألوان شريط الكاشير وشعار المحل 🎨': 'Couleurs de la Barre & Logo Caisse 🎨',
      'اختر اللون المفضل لشريط الكاشير وتخصيص هوية المتجر': 'Personnalisez la couleur de la barre de caisse et l\'identité du magasin',
      'اختر لغة التطبيق (Language)': 'Choisir la langue de l\'application',
      'نقداً (Espèces)': 'Espèces (Cash)',
      'بطاقة بنكية / الذهبية (TPE)': 'Carte Bancaire / CIB (TPE)',
      'بريدي باي (BaridiPay QR)': 'BaridiMob (BaridiPay QR)',
      'على الحساب / كريدي (Dette)': 'À crédit (Dette)',
      'دفع مجزأ (Paiement Partagé)': 'Paiement partagé (Split)',
      'المجموع الصافي للدفع': 'Net à payer',
      'طريقة الدفع': 'Mode de paiement',
      'المبلغ المدفوع (DA)': 'Montant versé (DA)',
      'المتبقي للزبون (الصرف)': 'Monnaie à rendre',
      'باكي (علبة 🟫)': 'Paquet (Boîte 🟫)',
      'كرطوشة (10 علب 📦)': 'Cartouche (10 boîtes 📦)',
      'بالسيجارة (Détail 🚬)': 'À la pièce / Détail 🚬',
      'بيع بالتجزئة (Détail)': 'Vente au détail (Détail)',
      'بيع بالجملة (Gros)': 'Vente en gros (Gros)',
      'سعر الجملة 📦': 'Prix de gros 📦',
      'الباركود: %barcode% • المخزون: %stock%': 'Code-barres: %barcode% • Stock: %stock%',
      'سلة المشتريات': 'Panier',
      'المجموع الإجمالي': 'Total Général',
      'المجموع': 'Total',
      'الكمية': 'Quantité',
      'السعر': 'Prix',
      'المنتج': 'Produit',
      'السلعة': 'Article',
      'اسم السلعة': 'Nom de l\'article',
      'اسم المنتج': 'Nom du produit',
      'سعر الشراء': 'Prix d\'achat',
      'سعر البيع': 'Prix de vente',
      'سعر التكلفة': 'Coût d\'achat',
      'سعر الجملة': 'Prix de gros',
      'سعر نصف الجملة': 'Prix demi-gros',
      'الكمية المخزنة': 'Stock disponible',
      'المخزون': 'Stock',
      'المخزن': 'Entrepôt',
      'الصنف': 'Catégorie',
      'الوحدة': 'Unité',
      'الباركود': 'Code-barres',
      'حفظ': 'Enregistrer',
      'إلغاء': 'Annuler',
      'تعديل': 'Modifier',
      'حذف': 'Supprimer',
      'تأكيد': 'Confirmer',
      'إغلاق': 'Fermer',
      'رجوع': 'Retour',
      'بحث': 'Recherche',
      'بحث...': 'Recherche...',
      'الكل': 'Tous',
      'إضافة': 'Ajouter',
      'إضافة منتج': 'Ajouter un produit',
      'تعديل منتج': 'Modifier le produit',
      'استلام السلع': 'Arrivage marchandise',
      'استلام السلع / Arrivage': 'Réception / Arrivage',
      'دفتر الديون': 'Carnet de dettes',
      'دفتر الكريدي والديون': 'Carnet de crédit (Dettes)',
      'التقرير اليومي': 'Rapport journalier',
      'تقرير اليومية والأرباح': 'Rapport & Bénéfices',
      'الإعدادات': 'Paramètres',
      'الإعدادات والخيارات': 'Paramètres & Options',
      'معلومات المتجر': 'Informations boutique',
      'المواد التبغية': 'Produits tabac',
      'المواد التبغية 🚬': 'Produits tabac 🚬',
      'سلات واردة': 'Paniers reçus',
      'ترتيب وتخصيص': 'Personnaliser',
      'ترتيب وتخصيص ⚙️': 'Personnaliser ⚙️',
      'تخفيض': 'Remise',
      'تخفيض (F4)': 'Remise (F4)',
      'تعليق': 'En attente',
      'تعليق (F2)': 'Attente (F2)',
      'دفع وفوترة': 'Paiement',
      'دفع وفوترة (F12)': 'Paiement (F12)',
      'فتح درج النقود (F10)': 'Ouvrir tiroir (F10)',
      'وضع الإرجاع': 'Mode retour',
      'وضع الإرجاع والاستبدال 🔄': 'Mode retour & échange 🔄',
      'تجزئة (F5)': 'Détail (F5)',
      'نصف جملة (F5)': 'Demi-gros (F5)',
      'جملة (F5)': 'Gros (F5)',
      'عدد المواد': 'Nombre d\'articles',
      'الإجمالي الصافي:': 'Total Net :',
      'إفراغ السلة': 'Vider le panier',
      'طباعة الوصل': 'Imprimer ticket',
      'تأكيد البيع وطباعة الوصل': 'Confirmer & Imprimer',
      'تأكيد وحفظ البيع': 'Confirmer la vente',
      'فاتورة جديدة': 'Nouveau ticket',
      'الرصيد': 'Solde',
      'المدفوع': 'Payé',
      'المتبقي': 'Reste',
      'الزبون': 'Client',
      'المورد': 'Fournisseur',
      'التاريخ': 'Date',
      'الوقت': 'Heure',
      'دج': 'DA',
      'حبة': 'Pièce',
      'علبة': 'Paquet',
      'كرتوشة': 'Cartouche',
      'كرتون': 'Carton',
      'كغ': 'Kg',
      'غرام': 'g',
      'لتر': 'L',
      'متر': 'm',
      'نعم': 'Oui',
      'لا': 'Non',
      'نشط': 'Actif',
      'معطل': 'Désactivé',
      'متصل': 'Connecté',
      'غير متصل': 'Déconnecté',
      'نجاح': 'Succès',
      'خطأ': 'Erreur',
      'تنبيه': 'Avertissement',
      'الوضع الداكن': 'Mode sombre',
      'الوضع الساطع': 'Mode clair',
      'الرئيسية': 'Accueil',
      'المنتجات': 'Produits',
      'الزبائن': 'Clients',
      'المبيعات': 'Ventes',
      'الأرباح': 'Bénéfices',
      'الورديات': 'Quarts',
      'فتح الوردية': 'Ouvrir quart',
      'إغلاق الوردية': 'Fermer quart',
      'سعر البيع بالتجزئة': 'Prix de vente détail',
      'سعر البيع بالجملة': 'Prix de gros',
      'الباركود الدولي': 'Code-barres',
      'الكمية الحالية': 'Quantité actuelle',
      'حد التنبيه': 'Seuil d\'alerte',
      'المورد الافتراضي': 'Fournisseur par défaut',
      'تاريخ الانتهاء': 'Date d\'expiration',
      'تفريغ': 'Effacer',
      'تصدير Excel': 'Exporter Excel',
      'استيراد': 'Importer',
      'نسخ احتياطي': 'Sauvegarde',
      'استرجاع': 'Restaurer',
      'تفعيل البرنامج': 'Activer le logiciel',
      'كود الجهاز': 'Code Machine',
      'مفتاح التفعيل': 'Clé d\'activation',
      'نسخ كود الجهاز': 'Copier le code',
      'تفعيل أوفلاين': 'Activer Hors-Ligne',
      'طلب تفعيل أونلاين': 'Demander l\'activation',
      'الباركود غير موجود': 'Code-barres introuvable',
      'تم حفظ التعديلات بنجاح': 'Modifications enregistrées',
      'تمت إضافة المنتج بنجاح': 'Produit ajouté avec succès',
      'تم الحذف بنجاح': 'Suppression réussie',
      'هل أنت متأكد؟': 'Êtes-vous sûr ?',
    },
    'en': {
      'سلة المشتريات': 'Shopping Cart',
      'المجموع الإجمالي': 'Grand Total',
      'المجموع': 'Total',
      'الكمية': 'Quantity',
      'السعر': 'Price',
      'المنتج': 'Product',
      'السلعة': 'Item',
      'اسم السلعة': 'Item Name',
      'اسم المنتج': 'Product Name',
      'سعر الشراء': 'Cost Price',
      'سعر البيع': 'Selling Price',
      'سعر التكلفة': 'Cost Price',
      'سعر الجملة': 'Wholesale Price',
      'سعر نصف الجملة': 'Semi-wholesale Price',
      'الكمية المخزنة': 'Available Stock',
      'المخزون': 'Stock',
      'المخزن': 'Warehouse',
      'الصنف': 'Category',
      'الوحدة': 'Unit',
      'الباركود': 'Barcode',
      'حفظ': 'Save',
      'إلغاء': 'Cancel',
      'تعديل': 'Edit',
      'حذف': 'Delete',
      'تأكيد': 'Confirm',
      'إغلاق': 'Close',
      'رجوع': 'Back',
      'بحث': 'Search',
      'بحث...': 'Search...',
      'الكل': 'All',
      'إضافة': 'Add',
      'إضافة منتج': 'Add Product',
      'تعديل منتج': 'Edit Product',
      'استلام السلع': 'Stock In',
      'استلام السلع / Arrivage': 'Stock In / Arrivage',
      'دفتر الديون': 'Credit Ledger',
      'دفتر الكريدي والديون': 'Credit & Debt Ledger',
      'التقرير اليومي': 'Daily Report',
      'تقرير اليومية والأرباح': 'Daily Report & Profits',
      'الإعدادات': 'Settings',
      'الإعدادات والخيارات': 'Settings & Options',
      'معلومات المتجر': 'Store Information',
      'المواد التبغية': 'Tobacco Products',
      'المواد التبغية 🚬': 'Tobacco Products 🚬',
      'سلات واردة': 'Incoming Carts',
      'ترتيب وتخصيص': 'Customize',
      'ترتيب وتخصيص ⚙️': 'Customize ⚙️',
      'تخفيض': 'Discount',
      'تخفيض (F4)': 'Discount (F4)',
      'تعليق': 'Hold',
      'تعليق (F2)': 'Hold (F2)',
      'دفع وفوترة': 'Checkout',
      'دفع وفوترة (F12)': 'Checkout (F12)',
      'فتح درج النقود (F10)': 'Open Drawer (F10)',
      'وضع الإرجاع': 'Return Mode',
      'وضع الإرجاع والاستبدال 🔄': 'Return & Exchange Mode 🔄',
      'تجزئة (F5)': 'Retail (F5)',
      'نصف جملة (F5)': 'Semi-wholesale (F5)',
      'جملة (F5)': 'Wholesale (F5)',
      'عدد المواد': 'Items Count',
      'الإجمالي الصافي:': 'Net Total:',
      'إفراغ السلة': 'Clear Cart',
      'طباعة الوصل': 'Print Receipt',
      'تأكيد البيع وطباعة الوصل': 'Confirm & Print',
      'تأكيد وحفظ البيع': 'Confirm Sale',
      'فاتورة جديدة': 'New Invoice',
      'الرصيد': 'Balance',
      'المدفوع': 'Paid',
      'المتبقي': 'Remaining',
      'الزبون': 'Customer',
      'المورد': 'Supplier',
      'التاريخ': 'Date',
      'الوقت': 'Time',
      'دج': 'DA',
      'حبة': 'Piece',
      'علبة': 'Pack',
      'كرتوشة': 'Carton',
      'كرتون': 'Box',
      'كغ': 'Kg',
      'غرام': 'g',
      'لتر': 'L',
      'متر': 'm',
      'نعم': 'Yes',
      'لا': 'No',
      'نشط': 'Active',
      'معطل': 'Disabled',
      'متصل': 'Connected',
      'غير متصل': 'Disconnected',
      'نجاح': 'Success',
      'خطأ': 'Error',
      'تنبيه': 'Warning',
      'الوضع الداكن': 'Dark Mode',
      'الوضع الساطع': 'Light Mode',
      'الرئيسية': 'Home',
      'المنتجات': 'Products',
      'الزبائن': 'Customers',
      'المبيعات': 'Sales',
      'الأرباح': 'Profits',
      'الورديات': 'Shifts',
      'فتح الوردية': 'Open Shift',
      'إغلاق الوردية': 'Close Shift',
      'سعر البيع بالتجزئة': 'Retail Price',
      'سعر البيع بالجملة': 'Wholesale Price',
      'الباركود الدولي': 'Barcode',
      'الكمية الحالية': 'Current Quantity',
      'حد التنبيه': 'Alert Threshold',
      'المورد الافتراضي': 'Default Supplier',
      'تاريخ الانتهاء': 'Expiry Date',
      'تفريغ': 'Clear',
      'تصدير Excel': 'Export to Excel',
      'استيراد': 'Import',
      'نسخ احتياطي': 'Backup',
      'استرجاع': 'Restore',
      'تفعيل البرنامج': 'Activate App',
      'كود الجهاز': 'Machine Code',
      'مفتاح التفعيل': 'Activation Key',
      'نسخ كود الجهاز': 'Copy Code',
      'تفعيل أوفلاين': 'Activate Offline',
      'طلب تفعيل أونلاين': 'Request Online Activation',
      'الباركود غير موجود': 'Barcode not found',
      'تم حفظ التعديلات بنجاح': 'Changes saved successfully',
      'تمت إضافة المنتج بنجاح': 'Product added successfully',
      'تم الحذف بنجاح': 'Deleted successfully',
      'هل أنت متأكد؟': 'Are you sure?',
    },
  };

  // Reverse mapping from Arabic values to Keys
  static late final Map<String, String> _arabicToKey = {
    for (final entry in _localizedValues['ar']!.entries)
      entry.value.trim(): entry.key,
  };

  String tr(String keyOrPhrase) {
    final clean = keyOrPhrase.trim();
    if (clean.isEmpty) return keyOrPhrase;

    // If target language is Arabic:
    if (locale.languageCode == 'ar') {
      // If it's a key in Arabic, return the Arabic value
      if (_localizedValues['ar']?.containsKey(clean) == true) {
        return _localizedValues['ar']![clean]!;
      }
      // Otherwise it is already in Arabic (or raw text)
      return keyOrPhrase;
    }

    final lang = locale.languageCode;

    // 1. Direct key match in target language
    if (_localizedValues[lang]?.containsKey(clean) == true) {
      return _localizedValues[lang]![clean]!;
    }

    // 2. Direct phrase match from phrase dictionary
    if (_phraseDictionary[lang]?.containsKey(clean) == true) {
      return _phraseDictionary[lang]![clean]!;
    }

    // 3. Reverse lookup from Arabic text to key
    final mappedKey = _arabicToKey[clean];
    if (mappedKey != null && _localizedValues[lang]?.containsKey(mappedKey) == true) {
      return _localizedValues[lang]![mappedKey]!;
    }

    // 4. Try stripping trailing colons or punctuation
    if (clean.endsWith(':') || clean.endsWith('：')) {
      final base = clean.substring(0, clean.length - 1).trim();
      final translated = tr(base);
      if (translated != base) {
        return '$translated :';
      }
    }

    // 5. Try case-insensitive / emoji-trimmed match
    for (final entry in _phraseDictionary[lang]?.entries ?? <MapEntry<String, String>>[]) {
      if (clean.contains(entry.key)) {
        return clean.replaceAll(entry.key, entry.value);
      }
    }

    // Fallback: return Arabic or original
    return _localizedValues['ar']?[clean] ?? keyOrPhrase;
  }

}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'fr', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension TranslationExtension on BuildContext {
  String tr(String key) => AppLocalizations.of(this).tr(key);
}

